#!/usr/bin/python3
# EASY-INSTALL-DEV-SCRIPT: 'bookarm-control-py==0.1.0','grasp_book'
__requires__ = 'bookarm-control-py==0.1.0'
__import__('pkg_resources').require('bookarm-control-py==0.1.0')
__file__ = '/home/boreas/project/bookarm-control-py/build/bookarm_control_py/ros2_scripts/grasp_book'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
