"""Default configuration values for point-pick grasp tasks."""

from __future__ import annotations

from pathlib import Path

import numpy as np


ACTION_X_MIN_CM = 20
ACTION_X_MAX_EXCLUSIVE_CM = 51
DEFAULT_TARGET_SAVE_PATH = Path("runs/grasp_book/last_target.json")

START_Q_DEG = np.array([0.0, -70.0, 60.0, 0.0, -45.0], dtype=float)
DEFAULT_AXIS_MAP = "z,-x,-y"
DEFAULT_OFFSET_MM = (300.0, -100.0, 0.0)
DEFAULT_CALIBRATION_PATH = Path("calibration/camera_to_base.json")
CAMERA_SERIAL = None
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
CAMERA_WARMUP_FRAMES = 30
CAMERA_TIMEOUT_MS = 5000
DEPTH_MIN_M = 0.0
DEPTH_MAX_M = 4.0
POINT_CLOUD_STRIDE = 1
VOXEL_SIZE_M = 0.0
PICK_POINT_SIZE = 1.0
POINT_INDEX = None
SAVE_PLY_PATH = None
FLIP_VIEW = True
TRANSFORM_MATRIX_PATH = None
USE_CALIBRATION_FILE = True
CAMERA_TO_BASE_XYZ_M = None
CAMERA_TO_BASE_RPY_DEG = None
TARGET_OFFSET_BASE_M = [0.0, 0.0, 0.0]
WORKSPACE_X_MIN_MM = 0.0
WORKSPACE_X_MAX_MM = 450.0
WORKSPACE_Y_MIN_MM = -300.0
WORKSPACE_Y_MAX_MM = 300.0
WORKSPACE_Z_MIN_MM = 20.0
WORKSPACE_Z_MAX_MM = 400.0
WORKSPACE_XY_RADIUS_MIN_MM = 40.0
WORKSPACE_XY_RADIUS_MAX_MM = 450.0
ARM_TEST = False
ARM_SPEED = 25.0
ARM_ACCELERATION = 5.0
ARM_WAIT_SECONDS = 5.0
GRIPPER_WAIT_SECONDS = 1.0

ACTION_REGULAR_SPEED = 25.0
ACTION_REGULAR_ACC = 8.0
